// This file is automatically generated. Do not edit it directly.
// TEMPORARY: Using mock client for testing due to Supabase API key issues
// TODO: Revert this change once Supabase is properly configured

// Uncomment the following lines when Supabase is working:
// import { createClient } from '@supabase/supabase-js'
// 
// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
// const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY
// 
// if (!SUPABASE_URL) {
//   throw new Error("VITE_SUPABASE_URL is not set")
// }
// if (!SUPABASE_ANON_KEY) {
//   throw new Error("VITE_SUPABASE_ANON_KEY is not set")
// }
// 
// export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// })

// Temporary mock client
export { supabase } from './mock-client.js'
